main = ".open-next/worker.js"
name = "wordle"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[route]
pattern = "wordle.prakashgamit.com/*"
zone_name = "prakashgamit.com"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
